///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyFrankCrum_EMP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EEOI9section recording.
    /// </summary>
    [TestModule("5cba7dc5-d707-409f-a6e3-98c4c33d0a4d", ModuleType.Recording, 1)]
    public partial class EEOI9section : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyFrankCrum_EMPRepository repository.
        /// </summary>
        public static MyFrankCrum_EMPRepository repo = MyFrankCrum_EMPRepository.Instance;

        static EEOI9section instance = new EEOI9section();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EEOI9section()
        {
            EEOI9_BirthLocattion = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EEOI9section Instance
        {
            get { return instance; }
        }

#region Variables

        string _EEOI9_BirthLocattion;

        /// <summary>
        /// Gets or sets the value of variable EEOI9_BirthLocattion.
        /// </summary>
        [TestVariable("b4699e99-8d92-4d8e-a332-ba2297a9da5b")]
        public string EEOI9_BirthLocattion
        {
            get { return _EEOI9_BirthLocattion; }
            set { _EEOI9_BirthLocattion = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Validaton -EEO/I-9 section
            Report.Log(ReportLevel.Info, "Section", "Validaton -EEO/I-9 section", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='EEO / I-9   ') on item 'EEOI9'.", repo.EEOI9Info, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.EEOI9Info, "InnerText", "EEO / I-9   ");
            Delay.Milliseconds(100);
            
            // Press Edit Button
            Report.Log(ReportLevel.Info, "Section", "Press Edit Button", new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EDIT_EEOI9Section' at Center.", repo.EDIT_EEOI9SectionInfo, new RecordItemIndex(3));
            repo.EDIT_EEOI9Section.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(4));
            Delay.Duration(5000, false);
            
            // Change one or more of the fields  The Undo Changes button will become enabled
            Report.Log(ReportLevel.Info, "Section", "Change one or more of the fields  The Undo Changes button will become enabled", new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CssKynsejIndicatorContainerMfcSelect3' at Center.", repo.ApplicationUnderTest.CssKynsejIndicatorContainerMfcSelect3Info, new RecordItemIndex(6));
            repo.ApplicationUnderTest.CssKynsejIndicatorContainerMfcSelect3.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.EEO_I_9State' at Center.", repo.ApplicationUnderTest.EEO_I_9StateInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.EEO_I_9State.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'UndoChanges'.", repo.UndoChangesInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.UndoChangesInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            // Press Undo Changes I The changes you made are reverted
            Report.Log(ReportLevel.Info, "Section", "Press Undo Changes I The changes you made are reverted", new RecordItemIndex(9));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BirthLocation' at Center.", repo.ApplicationUnderTest.BirthLocationInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.BirthLocation.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.BirthLocation' and assigning its value to variable 'EEOI9_BirthLocattion'.", repo.ApplicationUnderTest.BirthLocationInfo, new RecordItemIndex(11));
            EEOI9_BirthLocattion = repo.ApplicationUnderTest.BirthLocation.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Mumbai' on item 'ApplicationUnderTest.BirthLocation'.", repo.ApplicationUnderTest.BirthLocationInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.BirthLocation.Element.SetAttributeValue("TagValue", "Mumbai");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EEOI9UndoChanges' at Center.", repo.EEOI9UndoChangesInfo, new RecordItemIndex(13));
            repo.EEOI9UndoChanges.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$EEOI9_BirthLocattion) on item 'ApplicationUnderTest.BirthLocation'.", repo.ApplicationUnderTest.BirthLocationInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.ApplicationUnderTest.BirthLocationInfo, "TagValue", EEOI9_BirthLocattion);
            Delay.Milliseconds(100);
            
            // Make changes in the dialog box fields and press Save Changes
            Report.Log(ReportLevel.Info, "Section", "Make changes in the dialog box fields and press Save Changes", new RecordItemIndex(15));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BirthLocation' at Center.", repo.ApplicationUnderTest.BirthLocationInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.BirthLocation.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Mumbai' on item 'ApplicationUnderTest.BirthLocation'.", repo.ApplicationUnderTest.BirthLocationInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.BirthLocation.Element.SetAttributeValue("TagValue", "Mumbai");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SaveChanges1' at Center.", repo.ApplicationUnderTest.SaveChanges1Info, new RecordItemIndex(18));
            repo.ApplicationUnderTest.SaveChanges1.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
