///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyFrankCrum_EMP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Employees_Paging_Control recording.
    /// </summary>
    [TestModule("77696da7-02db-4ddc-b949-a0dfb387c5fc", ModuleType.Recording, 1)]
    public partial class Employees_Paging_Control : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyFrankCrum_EMPRepository repository.
        /// </summary>
        public static MyFrankCrum_EMPRepository repo = MyFrankCrum_EMPRepository.Instance;

        static Employees_Paging_Control instance = new Employees_Paging_Control();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Employees_Paging_Control()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Employees_Paging_Control Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable RepoURL.
        /// </summary>
        [TestVariable("c75816bd-3150-4b49-aa6d-f8479454f515")]
        public string RepoURL
        {
            get { return repo.RepoURL; }
            set { repo.RepoURL = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Confirm the double-right arrow takes you to the end of the list
            Report.Log(ReportLevel.Info, "Section", "Confirm the double-right arrow takes you to the end of the list", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PagingLastdoubleArrow' at 15;17.", repo.ApplicationUnderTest.PagingLastdoubleArrowInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.PagingLastdoubleArrow.Click("15;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(2));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.PagingLastPagedes'.", repo.ApplicationUnderTest.PagingLastPagedesInfo, new RecordItemIndex(3));
            Validate.Exists(repo.ApplicationUnderTest.PagingLastPagedesInfo);
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "After clicked  the double-right arrow takes you to the end of the list screenshot", null, false, new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(5));
            Delay.Duration(3000, false);
            
            // Confirm that the double-left arrow takes you to the beginning of the list
            Report.Log(ReportLevel.Info, "Section", "Confirm that the double-left arrow takes you to the beginning of the list", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PagingFirstdoubleArrow' at Center.", repo.ApplicationUnderTest.PagingFirstdoubleArrowInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.PagingFirstdoubleArrow.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(8));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.PagingFirstPageArrow'.", repo.ApplicationUnderTest.PagingFirstPageArrowInfo, new RecordItemIndex(9));
            Validate.Exists(repo.ApplicationUnderTest.PagingFirstPageArrowInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -557 units.", new RecordItemIndex(10));
            Mouse.ScrollWheel(-557);
            Delay.Milliseconds(300);
            
            Report.Screenshot(ReportLevel.Info, "User", "After clicked  that the double-left arrow takes you to the beginning of the list screenshot", null, false, new RecordItemIndex(11));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
