///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyFrankCrum_EMP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Home_Page_Validation recording.
    /// </summary>
    [TestModule("68fb4f80-1f19-4269-9640-e5079437e86c", ModuleType.Recording, 1)]
    public partial class Home_Page_Validation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyFrankCrum_EMPRepository repository.
        /// </summary>
        public static MyFrankCrum_EMPRepository repo = MyFrankCrum_EMPRepository.Instance;

        static Home_Page_Validation instance = new Home_Page_Validation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Home_Page_Validation()
        {
            RepoURL = "mfcqa01.frankcrum.com";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Home_Page_Validation Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable RepoURL.
        /// </summary>
        [TestVariable("c75816bd-3150-4b49-aa6d-f8479454f515")]
        public string RepoURL
        {
            get { return repo.RepoURL; }
            set { repo.RepoURL = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Latest Paycheck (Net Pay):') on item 'ApplicationUnderTest.LatestPaycheckNetPay'.", repo.ApplicationUnderTest.LatestPaycheckNetPayInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.LatestPaycheckNetPayInfo, "InnerText", "Latest Paycheck (Net Pay):");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Earnings This Tax Year:') on item 'ApplicationUnderTest.EarningsThisTaxYear'.", repo.ApplicationUnderTest.EarningsThisTaxYearInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.EarningsThisTaxYearInfo, "InnerText", "Earnings This Tax Year:");
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "After validate Paycheck net pay and earning  screenshot", repo.ApplicationUnderTest.Self, false, new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Company News') on item 'ApplicationUnderTest.CompanyNews'.", repo.ApplicationUnderTest.CompanyNewsInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.CompanyNewsInfo, "InnerText", "Company News");
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "After validate company news section   screenshot", repo.ApplicationUnderTest.Self, false, new RecordItemIndex(4));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
