///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyFrankCrum_EMP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The My_Resources recording.
    /// </summary>
    [TestModule("84a6772a-9519-4b16-9feb-c3641a6e1116", ModuleType.Recording, 1)]
    public partial class My_Resources : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyFrankCrum_EMPRepository repository.
        /// </summary>
        public static MyFrankCrum_EMPRepository repo = MyFrankCrum_EMPRepository.Instance;

        static My_Resources instance = new My_Resources();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public My_Resources()
        {
            SearchEmpName = "video";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static My_Resources Instance
        {
            get { return instance; }
        }

#region Variables

        string _SearchEmpName;

        /// <summary>
        /// Gets or sets the value of variable SearchEmpName.
        /// </summary>
        [TestVariable("e9c74fde-0358-4e03-bad6-9c834c2828c0")]
        public string SearchEmpName
        {
            get { return _SearchEmpName; }
            set { _SearchEmpName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable RepoURL.
        /// </summary>
        [TestVariable("c75816bd-3150-4b49-aa6d-f8479454f515")]
        public string RepoURL
        {
            get { return repo.RepoURL; }
            set { repo.RepoURL = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MyResources' at 34;11.", repo.ApplicationUnderTest.MyResourcesInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.MyResources.Click("34;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MyResourceSearchtext' at 85;23.", repo.ApplicationUnderTest.MyResourceSearchtextInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.MyResourceSearchtext.Click("85;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$SearchEmpName' with focus on 'ApplicationUnderTest.MyResourceSearchtext'.", repo.ApplicationUnderTest.MyResourceSearchtextInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.MyResourceSearchtext.PressKeys(SearchEmpName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Search1' at 85;15.", repo.ApplicationUnderTest.Search1Info, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Search1.Click("85;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(4));
            Delay.Duration(3000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "After search sreenshot taken", repo.ApplicationUnderTest.Self, false, new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Reset1' at 15;10.", repo.ApplicationUnderTest.Reset1Info, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Reset1.Click("15;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(7));
            Delay.Duration(3000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "After reset search sreenshot taken", repo.ApplicationUnderTest.Self, false, new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MyResourceSearchtext' at 85;23.", repo.ApplicationUnderTest.MyResourceSearchtextInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.MyResourceSearchtext.Click("85;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$SearchEmpName' with focus on 'ApplicationUnderTest.MyResourceSearchtext'.", repo.ApplicationUnderTest.MyResourceSearchtextInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.MyResourceSearchtext.PressKeys(SearchEmpName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Search1' at 85;15.", repo.ApplicationUnderTest.Search1Info, new RecordItemIndex(11));
            repo.ApplicationUnderTest.Search1.Click("85;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Contentview' at 67;9.", repo.ApplicationUnderTest.ContentviewInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.Contentview.Click("67;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(13));
            Delay.Duration(3000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "After click view  sreenshot taken", repo.ApplicationUnderTest.Self, false, new RecordItemIndex(14));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
