///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyFrankCrum_EMP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyFrankCrum_EMPRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("57aa7af5-e1bb-4d86-b1a0-d72cef37e59c")]
    public partial class MyFrankCrum_EMPRepository : RepoGenBaseFolder
    {
        static MyFrankCrum_EMPRepository instance = new MyFrankCrum_EMPRepository();
        MyFrankCrum_EMPRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyFrankCrum_EMPRepositoryFolders.MyFrankCrumAppFolder _myfrankcrum;
        MyFrankCrum_EMPRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the MyFrankCrum_EMPRepository element repository.
        /// </summary>
        [RepositoryFolder("57aa7af5-e1bb-4d86-b1a0-d72cef37e59c")]
        public static MyFrankCrum_EMPRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyFrankCrum_EMPRepository() 
            : base("MyFrankCrum_EMPRepository", "/", null, 0, false, "57aa7af5-e1bb-4d86-b1a0-d72cef37e59c", ".\\RepositoryImages\\MyFrankCrum_EMPRepository57aa7af5.rximgres")
        {
            _applicationundertest = new MyFrankCrum_EMPRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _myfrankcrum = new MyFrankCrum_EMPRepositoryFolders.MyFrankCrumAppFolder(this);
            _explorer = new MyFrankCrum_EMPRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

        string _CompPwd = "Crum2017";

        /// <summary>
        /// Gets or sets the value of variable CompPwd.
        /// </summary>
        [TestVariable("8e0ad58d-ed8f-4b1b-95b9-74118034f7b8")]
        public string CompPwd
        {
            get { return _CompPwd; }
            set { _CompPwd = value; }
        }

        string _CompName = "THS NATIONAL";

        /// <summary>
        /// Gets or sets the value of variable CompName.
        /// </summary>
        [TestVariable("0af2cb6b-977b-477f-9d28-dd11890b6f7f")]
        public string CompName
        {
            get { return _CompName; }
            set { _CompName = value; }
        }

        string _comselect = "21538";

        /// <summary>
        /// Gets or sets the value of variable comselect.
        /// </summary>
        [TestVariable("0d01ccb8-ab77-4f6b-b96b-a5688cbd15f7")]
        public string comselect
        {
            get { return _comselect; }
            set { _comselect = value; }
        }

        string _compselect = "";

        /// <summary>
        /// Gets or sets the value of variable compselect.
        /// </summary>
        [TestVariable("85249dde-7b5d-4085-b365-e16a9c0decdf")]
        public string compselect
        {
            get { return _compselect; }
            set { _compselect = value; }
        }

        string _Emp = "-1";

        /// <summary>
        /// Gets or sets the value of variable Emp.
        /// </summary>
        [TestVariable("c35b5cb9-165d-4d1f-910e-208448e73914")]
        public string Emp
        {
            get { return _Emp; }
            set { _Emp = value; }
        }

        string _EmpName = "Allen, Dane T";

        /// <summary>
        /// Gets or sets the value of variable EmpName.
        /// </summary>
        [TestVariable("63421979-03c2-4681-8118-3604485e880a")]
        public string EmpName
        {
            get { return _EmpName; }
            set { _EmpName = value; }
        }

        string _Sortingvalue = "Last Name: Z-A";

        /// <summary>
        /// Gets or sets the value of variable Sortingvalue.
        /// </summary>
        [TestVariable("f17c01d4-2115-4a8a-8535-c75aeffd4d53")]
        public string Sortingvalue
        {
            get { return _Sortingvalue; }
            set { _Sortingvalue = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("57aa7af5-e1bb-4d86-b1a0-d72cef37e59c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("4adb2402-d0f1-4185-819f-54d35157c656")]
        public virtual MyFrankCrum_EMPRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The MyFrankCrum folder.
        /// </summary>
        [RepositoryFolder("e02b0ef2-fe8d-4d4c-89ac-ddc5221f14bc")]
        public virtual MyFrankCrum_EMPRepositoryFolders.MyFrankCrumAppFolder MyFrankCrum
        {
            get { return _myfrankcrum; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("803f8440-3af5-460b-a814-d1d1b413f407")]
        public virtual MyFrankCrum_EMPRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyFrankCrum_EMPRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("4adb2402-d0f1-4185-819f-54d35157c656")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            MyFrankCrum_EMPRepositoryFolders.SomeDivTagFolder _somedivtag;
            MyFrankCrum_EMPRepositoryFolders.ReactTabsTabListFolder _reacttabstablist;
            MyFrankCrum_EMPRepositoryFolders.CssVnm4clReactTabsFolder _cssvnm4clreacttabs;
            RepoItemInfo _hiuserInfo;
            RepoItemInfo _pendingtimeoffrequests0Info;
            RepoItemInfo _timeoffcalendarInfo;
            RepoItemInfo _employeesInfo;
            RepoItemInfo _personalInfo;
            RepoItemInfo _jobpayInfo;
            RepoItemInfo _httpsdevmfcfrankcrumcomloginInfo;
            SidebarInfoClass _sidebarInfo;
            RepoItemInfo _setting1Info;
            RepoItemInfo _unifiedcheckInfo;
            SidebarContentContainerInfoClass _sidebarcontentcontainerInfo;
            RepoItemInfo _unifiedsettingsInfo;
            RepoItemInfo _stdcheckedInfo;
            RepoItemInfo _changecompanyInfo;
            RepoItemInfo _fasfatimesInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='devmfc.frankcrum.com']", parentFolder, 30000, null, false, "4adb2402-d0f1-4185-819f-54d35157c656", "")
            {
                _somedivtag = new MyFrankCrum_EMPRepositoryFolders.SomeDivTagFolder(this);
                _reacttabstablist = new MyFrankCrum_EMPRepositoryFolders.ReactTabsTabListFolder(this);
                _cssvnm4clreacttabs = new MyFrankCrum_EMPRepositoryFolders.CssVnm4clReactTabsFolder(this);
                _hiuserInfo = new RepoItemInfo(this, "HiUser", ".//div[#'app']/div[2]/div[3]/div/div/div[1]/div[@innertext='Hi, User!']", 30000, null, "a3e32600-6f6d-4dc7-b218-60c088d58d1d");
                _pendingtimeoffrequests0Info = new RepoItemInfo(this, "PendingTimeOffRequests0", ".//div[#'app']/div[2]/div[3]/div/div/div[2]/div[1]/div[1]/?/?/div[@innertext>'Pending Time Off Requests']", 30000, null, "c56020f0-77cb-4f3b-959c-9530964f1a71");
                _timeoffcalendarInfo = new RepoItemInfo(this, "TimeOffCalendar", ".//div[#'app']/div[2]/div[3]/div/div/div[2]/?/?/h5[@innertext='Time Off Calendar']", 30000, null, "b0975e3b-721e-4b0e-87b0-893b6f26a04c");
                _employeesInfo = new RepoItemInfo(this, "Employees", ".//div[#'/Employees']//div[@innertext='Employees']", 30000, null, "4c761a55-0c84-4b80-b662-f8ba98ff564f");
                _personalInfo = new RepoItemInfo(this, "Personal", ".//div[#'app']/div[2]/div[3]/div/div[4]/div[1]/ul/?/?/li[@innertext='Personal']", 30000, null, "18137ebf-5c2e-48a0-b589-8241b8c342d1");
                _jobpayInfo = new RepoItemInfo(this, "JobPay", ".//div[#'app']/div[2]/div[3]/div/div[4]/div[1]/ul/?/?/li[@innertext='Job & Pay']", 30000, null, "663ab337-b10c-4767-94a3-3dc45d8bdddb");
                _httpsdevmfcfrankcrumcomloginInfo = new RepoItemInfo(this, "HttpsDevmfcFrankcrumComLogin", ".//div[#'app']/div[2]//form[@action='https://devmfc.frankcrum.com/login']", 30000, null, "87755aa0-4c28-427f-8187-0b59e947f128");
                _sidebarInfo = new SidebarInfoClass(this);
                _setting1Info = new RepoItemInfo(this, "setting1", ".//div[#'sidebar-content-container']//a[@innertext='Settings']", 30000, null, "3cf03341-f3d9-4bb3-96f5-553c274f4647");
                _unifiedcheckInfo = new RepoItemInfo(this, "UnifiedCheck", ".//div[#'app']/div[2]/div[3]//form[@action='https://devmfc.frankcrum.com/employerSettings']/div/div[3]/div[2]/label[2]/span[@id='checkmark']", 30000, null, "1f820e1a-b0da-498e-8f42-36439557f0d9");
                _sidebarcontentcontainerInfo = new SidebarContentContainerInfoClass(this);
                _unifiedsettingsInfo = new RepoItemInfo(this, "Unifiedsettings", ".//div[#'sidebar-content-container']/div[6]//a[@innertext='Settings']", 30000, null, "25534b36-d813-46ce-a4d1-672f5afc5206");
                _stdcheckedInfo = new RepoItemInfo(this, "Stdchecked", ".//div[#'app']/div[2]/div[3]//form[@action='https://devmfc.frankcrum.com/employerSettings']/div/div[3]//span[@id='checkmark']", 30000, null, "1fbf9ab4-609f-4efe-a079-eabfb7e6f4fe");
                _changecompanyInfo = new RepoItemInfo(this, "ChangeCompany", ".//div[#'app']/div[2]/div[1]/div/div[3]//button[@innertext='Change Company']", 30000, null, "79999ea6-8702-4994-a99f-069ba20c0895");
                _fasfatimesInfo = new RepoItemInfo(this, "FasFaTimes", ".//button[#'modal-close-button']/i", 30000, null, "95b54a4b-f8d8-4cf2-bf96-8cdfb96bb13d");
            }

            /// <summary>
            /// The SidebarInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("3942733e-6a7d-4b8f-8c7b-e0872aee717e")]
            public class SidebarInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SidebarInfoClass class constructor.
                /// </summary>
                public SidebarInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Sidebar", ".//div[#'app']/div[2]/div[2]", 30000, null, "3942733e-6a7d-4b8f-8c7b-e0872aee717e")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("7b4aaf44-72d6-46f0-9317-62fd81de1685")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("7b4aaf44-72d6-46f0-9317-62fd81de1685");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("7b4aaf44-72d6-46f0-9317-62fd81de1685")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("7b4aaf44-72d6-46f0-9317-62fd81de1685", cropRect);
                }
            }

            /// <summary>
            /// The SidebarContentContainerInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("a359618d-729f-4cf8-824d-fde5af5cb1ba")]
            public class SidebarContentContainerInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SidebarContentContainerInfoClass class constructor.
                /// </summary>
                public SidebarContentContainerInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SidebarContentContainer", ".//div[#'sidebar-content-container']", 30000, null, "a359618d-729f-4cf8-824d-fde5af5cb1ba")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("1b2567a6-06b3-477c-b049-7d36fc89e78c")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("1b2567a6-06b3-477c-b049-7d36fc89e78c");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("1b2567a6-06b3-477c-b049-7d36fc89e78c")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("1b2567a6-06b3-477c-b049-7d36fc89e78c", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("ef3b6f62-1622-4974-8188-202c0491b134")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("ef3b6f62-1622-4974-8188-202c0491b134");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("ef3b6f62-1622-4974-8188-202c0491b134")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("ef3b6f62-1622-4974-8188-202c0491b134", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4adb2402-d0f1-4185-819f-54d35157c656")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4adb2402-d0f1-4185-819f-54d35157c656")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HiUser item.
            /// </summary>
            [RepositoryItem("a3e32600-6f6d-4dc7-b218-60c088d58d1d")]
            public virtual Ranorex.DivTag HiUser
            {
                get
                {
                    return _hiuserInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The HiUser item info.
            /// </summary>
            [RepositoryItemInfo("a3e32600-6f6d-4dc7-b218-60c088d58d1d")]
            public virtual RepoItemInfo HiUserInfo
            {
                get
                {
                    return _hiuserInfo;
                }
            }

            /// <summary>
            /// The PendingTimeOffRequests0 item.
            /// </summary>
            [RepositoryItem("c56020f0-77cb-4f3b-959c-9530964f1a71")]
            public virtual Ranorex.DivTag PendingTimeOffRequests0
            {
                get
                {
                    return _pendingtimeoffrequests0Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PendingTimeOffRequests0 item info.
            /// </summary>
            [RepositoryItemInfo("c56020f0-77cb-4f3b-959c-9530964f1a71")]
            public virtual RepoItemInfo PendingTimeOffRequests0Info
            {
                get
                {
                    return _pendingtimeoffrequests0Info;
                }
            }

            /// <summary>
            /// The TimeOffCalendar item.
            /// </summary>
            [RepositoryItem("b0975e3b-721e-4b0e-87b0-893b6f26a04c")]
            public virtual Ranorex.H5Tag TimeOffCalendar
            {
                get
                {
                    return _timeoffcalendarInfo.CreateAdapter<Ranorex.H5Tag>(true);
                }
            }

            /// <summary>
            /// The TimeOffCalendar item info.
            /// </summary>
            [RepositoryItemInfo("b0975e3b-721e-4b0e-87b0-893b6f26a04c")]
            public virtual RepoItemInfo TimeOffCalendarInfo
            {
                get
                {
                    return _timeoffcalendarInfo;
                }
            }

            /// <summary>
            /// The Employees item.
            /// </summary>
            [RepositoryItem("4c761a55-0c84-4b80-b662-f8ba98ff564f")]
            public virtual Ranorex.DivTag Employees
            {
                get
                {
                    return _employeesInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Employees item info.
            /// </summary>
            [RepositoryItemInfo("4c761a55-0c84-4b80-b662-f8ba98ff564f")]
            public virtual RepoItemInfo EmployeesInfo
            {
                get
                {
                    return _employeesInfo;
                }
            }

            /// <summary>
            /// The Personal item.
            /// </summary>
            [RepositoryItem("18137ebf-5c2e-48a0-b589-8241b8c342d1")]
            public virtual Ranorex.LiTag Personal
            {
                get
                {
                    return _personalInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Personal item info.
            /// </summary>
            [RepositoryItemInfo("18137ebf-5c2e-48a0-b589-8241b8c342d1")]
            public virtual RepoItemInfo PersonalInfo
            {
                get
                {
                    return _personalInfo;
                }
            }

            /// <summary>
            /// The JobPay item.
            /// </summary>
            [RepositoryItem("663ab337-b10c-4767-94a3-3dc45d8bdddb")]
            public virtual Ranorex.LiTag JobPay
            {
                get
                {
                    return _jobpayInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The JobPay item info.
            /// </summary>
            [RepositoryItemInfo("663ab337-b10c-4767-94a3-3dc45d8bdddb")]
            public virtual RepoItemInfo JobPayInfo
            {
                get
                {
                    return _jobpayInfo;
                }
            }

            /// <summary>
            /// The HttpsDevmfcFrankcrumComLogin item.
            /// </summary>
            [RepositoryItem("87755aa0-4c28-427f-8187-0b59e947f128")]
            public virtual Ranorex.FormTag HttpsDevmfcFrankcrumComLogin
            {
                get
                {
                    return _httpsdevmfcfrankcrumcomloginInfo.CreateAdapter<Ranorex.FormTag>(true);
                }
            }

            /// <summary>
            /// The HttpsDevmfcFrankcrumComLogin item info.
            /// </summary>
            [RepositoryItemInfo("87755aa0-4c28-427f-8187-0b59e947f128")]
            public virtual RepoItemInfo HttpsDevmfcFrankcrumComLoginInfo
            {
                get
                {
                    return _httpsdevmfcfrankcrumcomloginInfo;
                }
            }

            /// <summary>
            /// The Sidebar item.
            /// </summary>
            [RepositoryItem("3942733e-6a7d-4b8f-8c7b-e0872aee717e")]
            public virtual Ranorex.DivTag Sidebar
            {
                get
                {
                    return _sidebarInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Sidebar item info.
            /// </summary>
            [RepositoryItemInfo("3942733e-6a7d-4b8f-8c7b-e0872aee717e")]
            public virtual SidebarInfoClass SidebarInfo
            {
                get
                {
                    return _sidebarInfo;
                }
            }

            /// <summary>
            /// The setting1 item.
            /// </summary>
            [RepositoryItem("3cf03341-f3d9-4bb3-96f5-553c274f4647")]
            public virtual Ranorex.ATag setting1
            {
                get
                {
                    return _setting1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The setting1 item info.
            /// </summary>
            [RepositoryItemInfo("3cf03341-f3d9-4bb3-96f5-553c274f4647")]
            public virtual RepoItemInfo setting1Info
            {
                get
                {
                    return _setting1Info;
                }
            }

            /// <summary>
            /// The UnifiedCheck item.
            /// </summary>
            [RepositoryItem("1f820e1a-b0da-498e-8f42-36439557f0d9")]
            public virtual Ranorex.SpanTag UnifiedCheck
            {
                get
                {
                    return _unifiedcheckInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UnifiedCheck item info.
            /// </summary>
            [RepositoryItemInfo("1f820e1a-b0da-498e-8f42-36439557f0d9")]
            public virtual RepoItemInfo UnifiedCheckInfo
            {
                get
                {
                    return _unifiedcheckInfo;
                }
            }

            /// <summary>
            /// The SidebarContentContainer item.
            /// </summary>
            [RepositoryItem("a359618d-729f-4cf8-824d-fde5af5cb1ba")]
            public virtual Ranorex.DivTag SidebarContentContainer
            {
                get
                {
                    return _sidebarcontentcontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SidebarContentContainer item info.
            /// </summary>
            [RepositoryItemInfo("a359618d-729f-4cf8-824d-fde5af5cb1ba")]
            public virtual SidebarContentContainerInfoClass SidebarContentContainerInfo
            {
                get
                {
                    return _sidebarcontentcontainerInfo;
                }
            }

            /// <summary>
            /// The Unifiedsettings item.
            /// </summary>
            [RepositoryItem("25534b36-d813-46ce-a4d1-672f5afc5206")]
            public virtual Ranorex.ATag Unifiedsettings
            {
                get
                {
                    return _unifiedsettingsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Unifiedsettings item info.
            /// </summary>
            [RepositoryItemInfo("25534b36-d813-46ce-a4d1-672f5afc5206")]
            public virtual RepoItemInfo UnifiedsettingsInfo
            {
                get
                {
                    return _unifiedsettingsInfo;
                }
            }

            /// <summary>
            /// The Stdchecked item.
            /// </summary>
            [RepositoryItem("1fbf9ab4-609f-4efe-a079-eabfb7e6f4fe")]
            public virtual Ranorex.SpanTag Stdchecked
            {
                get
                {
                    return _stdcheckedInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Stdchecked item info.
            /// </summary>
            [RepositoryItemInfo("1fbf9ab4-609f-4efe-a079-eabfb7e6f4fe")]
            public virtual RepoItemInfo StdcheckedInfo
            {
                get
                {
                    return _stdcheckedInfo;
                }
            }

            /// <summary>
            /// The ChangeCompany item.
            /// </summary>
            [RepositoryItem("79999ea6-8702-4994-a99f-069ba20c0895")]
            public virtual Ranorex.ButtonTag ChangeCompany
            {
                get
                {
                    return _changecompanyInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ChangeCompany item info.
            /// </summary>
            [RepositoryItemInfo("79999ea6-8702-4994-a99f-069ba20c0895")]
            public virtual RepoItemInfo ChangeCompanyInfo
            {
                get
                {
                    return _changecompanyInfo;
                }
            }

            /// <summary>
            /// The FasFaTimes item.
            /// </summary>
            [RepositoryItem("95b54a4b-f8d8-4cf2-bf96-8cdfb96bb13d")]
            public virtual Ranorex.ITag FasFaTimes
            {
                get
                {
                    return _fasfatimesInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FasFaTimes item info.
            /// </summary>
            [RepositoryItemInfo("95b54a4b-f8d8-4cf2-bf96-8cdfb96bb13d")]
            public virtual RepoItemInfo FasFaTimesInfo
            {
                get
                {
                    return _fasfatimesInfo;
                }
            }

            /// <summary>
            /// The SomeDivTag folder.
            /// </summary>
            [RepositoryFolder("3c277c0b-840f-4617-a705-75fe26324e8e")]
            public virtual MyFrankCrum_EMPRepositoryFolders.SomeDivTagFolder SomeDivTag
            {
                get { return _somedivtag; }
            }

            /// <summary>
            /// The ReactTabsTabList folder.
            /// </summary>
            [RepositoryFolder("5c790e60-8f13-4c69-8197-7fd2f571bc9a")]
            public virtual MyFrankCrum_EMPRepositoryFolders.ReactTabsTabListFolder ReactTabsTabList
            {
                get { return _reacttabstablist; }
            }

            /// <summary>
            /// The CssVnm4clReactTabs folder.
            /// </summary>
            [RepositoryFolder("c968c047-9605-45d4-ac8c-1b761d026102")]
            public virtual MyFrankCrum_EMPRepositoryFolders.CssVnm4clReactTabsFolder CssVnm4clReactTabs
            {
                get { return _cssvnm4clreacttabs; }
            }
        }

        /// <summary>
        /// The SomeDivTagFolder folder.
        /// </summary>
        [RepositoryFolder("3c277c0b-840f-4617-a705-75fe26324e8e")]
        public partial class SomeDivTagFolder : RepoGenBaseFolder
        {
            RepoItemInfo _findemployeeInfo;
            RepoItemInfo _searchInfo;
            RepoItemInfo _selectempInfo;
            SettingsInfoClass _settingsInfo;
            RepoItemInfo _checkmarkInfo;
            RepoItemInfo _flexrowInfo;
            FlexRow1InfoClass _flexrow1Info;
            RepoItemInfo _companynewsInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _active132Info;
            RepoItemInfo _leaveofabsence6Info;
            RepoItemInfo _onstrike2Info;
            RepoItemInfo _terminated20Info;
            RepoItemInfo _total160Info;
            RepoItemInfo _facaretdownfasInfo;
            RepoItemInfo _sortingvalueInfo;

            /// <summary>
            /// Creates a new SomeDivTag  folder.
            /// </summary>
            public SomeDivTagFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeDivTag", ".//div[#'app']/div[2]/div[3]/div/div[3]", parentFolder, 30000, null, false, "3c277c0b-840f-4617-a705-75fe26324e8e", "")
            {
                _findemployeeInfo = new RepoItemInfo(this, "FindEmployee", ".//form[@action='https://devmfc.frankcrum.com/Employees']/button[@innertext='Find Employee']", 30000, null, "4a94201e-15df-4f15-b447-e46ce28162b6");
                _searchInfo = new RepoItemInfo(this, "Search", ".//form[@action='https://devmfc.frankcrum.com/Employees']/input[@name='search']", 30000, null, "1afcd6c6-15d5-4d92-9d42-cfeaefa208ad");
                _selectempInfo = new RepoItemInfo(this, "selectEmp", "div/div/div[3]/div/div/div/div/div[2]/?/?/button[@innertext>$EmpName]", 30000, null, "525585a1-9415-4e8e-ba21-a47ab7c00a61");
                _settingsInfo = new SettingsInfoClass(this);
                _checkmarkInfo = new RepoItemInfo(this, "Checkmark", ".//form[@action='https://devmfc.frankcrum.com/employerSettings']/div[2]/div[3]/div[2]/label[2]/span[@id='checkmark']", 30000, null, "df4191fd-fee2-4754-a9ce-409dcb4c1a2f");
                _flexrowInfo = new RepoItemInfo(this, "FlexRow", "div[2]/div/div[3]/div/div/div[3]/div[1]/div/div/div[3]", 30000, null, "63dab18b-f28c-41a0-8d2a-666d6ac5f495");
                _flexrow1Info = new FlexRow1InfoClass(this);
                _companynewsInfo = new RepoItemInfo(this, "CompanyNews", "div[3]/?/?/h5[@innertext='Company News']", 30000, null, "33af1f85-8400-4a4c-b421-dc803b640fb5");
                _logoutInfo = new RepoItemInfo(this, "Logout", "div[4]/?/?/button[@innertext='Logout']", 30000, null, "60ce660e-aa29-40d8-b878-6c0aa16cb30b");
                _active132Info = new RepoItemInfo(this, "Active132", ".//ul/li[@innertext='Active (132)']", 30000, null, "75c40658-b487-495a-9e6e-bea3790a1bd7");
                _leaveofabsence6Info = new RepoItemInfo(this, "LeaveOfAbsence6", ".//ul/li[@innertext='Leave of absence (6)']", 30000, null, "5772e0a7-03db-4fd1-a9dd-5a090744deea");
                _onstrike2Info = new RepoItemInfo(this, "OnStrike2", ".//ul/li[@innertext='On strike (2)']", 30000, null, "9788da96-1f4c-412c-950d-971561d6566e");
                _terminated20Info = new RepoItemInfo(this, "Terminated20", ".//ul/li[@innertext='Terminated (20)']", 30000, null, "c603ab89-3f82-42b3-8191-24a1461e0207");
                _total160Info = new RepoItemInfo(this, "Total160", ".//ul/li[@innertext='Total (160)']", 30000, null, "68a90e47-c0e7-47a0-82ff-aa94f5e9f2ee");
                _facaretdownfasInfo = new RepoItemInfo(this, "FaCaretDownFas", "div/div/div[2]/div/div[2]//i", 30000, null, "c7ff59fd-bd34-493f-9547-e33cf49caa68");
                _sortingvalueInfo = new RepoItemInfo(this, "Sortingvalue", "div/div/div[2]/div/div[2]//div[@innertext=$Sortingvalue]", 30000, null, "69a94bb6-600b-4987-871c-9dc6601e49f8");
            }

            /// <summary>
            /// The SettingsInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("b8a642b7-927a-4482-a911-dbe530d2cecd")]
            public class SettingsInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SettingsInfoClass class constructor.
                /// </summary>
                public SettingsInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Settings", "div[9]//a[@innertext='Settings']", 30000, null, "b8a642b7-927a-4482-a911-dbe530d2cecd")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("5e9b78e6-f47e-453d-ad2c-4e22b4a17e1c")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("5e9b78e6-f47e-453d-ad2c-4e22b4a17e1c");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("5e9b78e6-f47e-453d-ad2c-4e22b4a17e1c")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("5e9b78e6-f47e-453d-ad2c-4e22b4a17e1c", cropRect);
                }
            }

            /// <summary>
            /// The FlexRow1InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("551cf9c5-f471-44f9-bff1-b2f174bbaa57")]
            public class FlexRow1InfoClass : RepoItemInfo
            {
                /// <summary>
                /// FlexRow1InfoClass class constructor.
                /// </summary>
                public FlexRow1InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "FlexRow1", "div[2]/div/div[3]/div/div/div[3]/div[1]/div/div/div[2]", 30000, null, "551cf9c5-f471-44f9-bff1-b2f174bbaa57")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("8b183d05-a722-493a-9f59-1d2bae68a389")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("8b183d05-a722-493a-9f59-1d2bae68a389");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("8b183d05-a722-493a-9f59-1d2bae68a389")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("8b183d05-a722-493a-9f59-1d2bae68a389", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3c277c0b-840f-4617-a705-75fe26324e8e")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3c277c0b-840f-4617-a705-75fe26324e8e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FindEmployee item.
            /// </summary>
            [RepositoryItem("4a94201e-15df-4f15-b447-e46ce28162b6")]
            public virtual Ranorex.ButtonTag FindEmployee
            {
                get
                {
                    return _findemployeeInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The FindEmployee item info.
            /// </summary>
            [RepositoryItemInfo("4a94201e-15df-4f15-b447-e46ce28162b6")]
            public virtual RepoItemInfo FindEmployeeInfo
            {
                get
                {
                    return _findemployeeInfo;
                }
            }

            /// <summary>
            /// The Search item.
            /// </summary>
            [RepositoryItem("1afcd6c6-15d5-4d92-9d42-cfeaefa208ad")]
            public virtual Ranorex.InputTag Search
            {
                get
                {
                    return _searchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Search item info.
            /// </summary>
            [RepositoryItemInfo("1afcd6c6-15d5-4d92-9d42-cfeaefa208ad")]
            public virtual RepoItemInfo SearchInfo
            {
                get
                {
                    return _searchInfo;
                }
            }

            /// <summary>
            /// The selectEmp item.
            /// </summary>
            [RepositoryItem("525585a1-9415-4e8e-ba21-a47ab7c00a61")]
            public virtual Ranorex.ButtonTag selectEmp
            {
                get
                {
                    return _selectempInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The selectEmp item info.
            /// </summary>
            [RepositoryItemInfo("525585a1-9415-4e8e-ba21-a47ab7c00a61")]
            public virtual RepoItemInfo selectEmpInfo
            {
                get
                {
                    return _selectempInfo;
                }
            }

            /// <summary>
            /// The Settings item.
            /// </summary>
            [RepositoryItem("b8a642b7-927a-4482-a911-dbe530d2cecd")]
            public virtual Ranorex.ATag Settings
            {
                get
                {
                    return _settingsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Settings item info.
            /// </summary>
            [RepositoryItemInfo("b8a642b7-927a-4482-a911-dbe530d2cecd")]
            public virtual SettingsInfoClass SettingsInfo
            {
                get
                {
                    return _settingsInfo;
                }
            }

            /// <summary>
            /// The Checkmark item.
            /// </summary>
            [RepositoryItem("df4191fd-fee2-4754-a9ce-409dcb4c1a2f")]
            public virtual Ranorex.SpanTag Checkmark
            {
                get
                {
                    return _checkmarkInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Checkmark item info.
            /// </summary>
            [RepositoryItemInfo("df4191fd-fee2-4754-a9ce-409dcb4c1a2f")]
            public virtual RepoItemInfo CheckmarkInfo
            {
                get
                {
                    return _checkmarkInfo;
                }
            }

            /// <summary>
            /// The FlexRow item.
            /// </summary>
            [RepositoryItem("63dab18b-f28c-41a0-8d2a-666d6ac5f495")]
            public virtual Ranorex.DivTag FlexRow
            {
                get
                {
                    return _flexrowInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FlexRow item info.
            /// </summary>
            [RepositoryItemInfo("63dab18b-f28c-41a0-8d2a-666d6ac5f495")]
            public virtual RepoItemInfo FlexRowInfo
            {
                get
                {
                    return _flexrowInfo;
                }
            }

            /// <summary>
            /// The FlexRow1 item.
            /// </summary>
            [RepositoryItem("551cf9c5-f471-44f9-bff1-b2f174bbaa57")]
            public virtual Ranorex.DivTag FlexRow1
            {
                get
                {
                    return _flexrow1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FlexRow1 item info.
            /// </summary>
            [RepositoryItemInfo("551cf9c5-f471-44f9-bff1-b2f174bbaa57")]
            public virtual FlexRow1InfoClass FlexRow1Info
            {
                get
                {
                    return _flexrow1Info;
                }
            }

            /// <summary>
            /// The CompanyNews item.
            /// </summary>
            [RepositoryItem("33af1f85-8400-4a4c-b421-dc803b640fb5")]
            public virtual Ranorex.H5Tag CompanyNews
            {
                get
                {
                    return _companynewsInfo.CreateAdapter<Ranorex.H5Tag>(true);
                }
            }

            /// <summary>
            /// The CompanyNews item info.
            /// </summary>
            [RepositoryItemInfo("33af1f85-8400-4a4c-b421-dc803b640fb5")]
            public virtual RepoItemInfo CompanyNewsInfo
            {
                get
                {
                    return _companynewsInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("60ce660e-aa29-40d8-b878-6c0aa16cb30b")]
            public virtual Ranorex.ButtonTag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("60ce660e-aa29-40d8-b878-6c0aa16cb30b")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The Active132 item.
            /// </summary>
            [RepositoryItem("75c40658-b487-495a-9e6e-bea3790a1bd7")]
            public virtual Ranorex.LiTag Active132
            {
                get
                {
                    return _active132Info.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Active132 item info.
            /// </summary>
            [RepositoryItemInfo("75c40658-b487-495a-9e6e-bea3790a1bd7")]
            public virtual RepoItemInfo Active132Info
            {
                get
                {
                    return _active132Info;
                }
            }

            /// <summary>
            /// The LeaveOfAbsence6 item.
            /// </summary>
            [RepositoryItem("5772e0a7-03db-4fd1-a9dd-5a090744deea")]
            public virtual Ranorex.LiTag LeaveOfAbsence6
            {
                get
                {
                    return _leaveofabsence6Info.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LeaveOfAbsence6 item info.
            /// </summary>
            [RepositoryItemInfo("5772e0a7-03db-4fd1-a9dd-5a090744deea")]
            public virtual RepoItemInfo LeaveOfAbsence6Info
            {
                get
                {
                    return _leaveofabsence6Info;
                }
            }

            /// <summary>
            /// The OnStrike2 item.
            /// </summary>
            [RepositoryItem("9788da96-1f4c-412c-950d-971561d6566e")]
            public virtual Ranorex.LiTag OnStrike2
            {
                get
                {
                    return _onstrike2Info.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The OnStrike2 item info.
            /// </summary>
            [RepositoryItemInfo("9788da96-1f4c-412c-950d-971561d6566e")]
            public virtual RepoItemInfo OnStrike2Info
            {
                get
                {
                    return _onstrike2Info;
                }
            }

            /// <summary>
            /// The Terminated20 item.
            /// </summary>
            [RepositoryItem("c603ab89-3f82-42b3-8191-24a1461e0207")]
            public virtual Ranorex.LiTag Terminated20
            {
                get
                {
                    return _terminated20Info.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Terminated20 item info.
            /// </summary>
            [RepositoryItemInfo("c603ab89-3f82-42b3-8191-24a1461e0207")]
            public virtual RepoItemInfo Terminated20Info
            {
                get
                {
                    return _terminated20Info;
                }
            }

            /// <summary>
            /// The Total160 item.
            /// </summary>
            [RepositoryItem("68a90e47-c0e7-47a0-82ff-aa94f5e9f2ee")]
            public virtual Ranorex.LiTag Total160
            {
                get
                {
                    return _total160Info.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Total160 item info.
            /// </summary>
            [RepositoryItemInfo("68a90e47-c0e7-47a0-82ff-aa94f5e9f2ee")]
            public virtual RepoItemInfo Total160Info
            {
                get
                {
                    return _total160Info;
                }
            }

            /// <summary>
            /// The FaCaretDownFas item.
            /// </summary>
            [RepositoryItem("c7ff59fd-bd34-493f-9547-e33cf49caa68")]
            public virtual Ranorex.ITag FaCaretDownFas
            {
                get
                {
                    return _facaretdownfasInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaCaretDownFas item info.
            /// </summary>
            [RepositoryItemInfo("c7ff59fd-bd34-493f-9547-e33cf49caa68")]
            public virtual RepoItemInfo FaCaretDownFasInfo
            {
                get
                {
                    return _facaretdownfasInfo;
                }
            }

            /// <summary>
            /// The Sortingvalue item.
            /// </summary>
            [RepositoryItem("69a94bb6-600b-4987-871c-9dc6601e49f8")]
            public virtual Ranorex.DivTag Sortingvalue
            {
                get
                {
                    return _sortingvalueInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Sortingvalue item info.
            /// </summary>
            [RepositoryItemInfo("69a94bb6-600b-4987-871c-9dc6601e49f8")]
            public virtual RepoItemInfo SortingvalueInfo
            {
                get
                {
                    return _sortingvalueInfo;
                }
            }
        }

        /// <summary>
        /// The ReactTabsTabListFolder folder.
        /// </summary>
        [RepositoryFolder("5c790e60-8f13-4c69-8197-7fd2f571bc9a")]
        public partial class ReactTabsTabListFolder : RepoGenBaseFolder
        {
            RepoItemInfo _deductionsInfo;
            RepoItemInfo _directdepositInfo;
            RepoItemInfo _documentsInfo;
            RepoItemInfo _earningsInfo;
            RepoItemInfo _historyInfo;
            RepoItemInfo _licensesInfo;
            RepoItemInfo _ptosetupInfo;
            RepoItemInfo _litagptoInfo;
            RepoItemInfo _payhistoryInfo;
            RepoItemInfo _taxesInfo;

            /// <summary>
            /// Creates a new ReactTabsTabList  folder.
            /// </summary>
            public ReactTabsTabListFolder(RepoGenBaseFolder parentFolder) :
                    base("ReactTabsTabList", ".//div[#'app']/div[2]/div[3]/div/div[4]/div[1]/ul", parentFolder, 30000, null, false, "5c790e60-8f13-4c69-8197-7fd2f571bc9a", "")
            {
                _deductionsInfo = new RepoItemInfo(this, "Deductions", "?/?/li[@innertext='Deductions']", 30000, null, "c01e2383-e9c4-4565-b771-190f973eba43");
                _directdepositInfo = new RepoItemInfo(this, "DirectDeposit", "?/?/li[@innertext='Direct Deposit']", 30000, null, "9442c2e2-d591-47b0-9964-f775bd261441");
                _documentsInfo = new RepoItemInfo(this, "Documents", "?/?/li[@innertext='Documents']", 30000, null, "689f8271-ab06-4b52-9f35-91d373d1af68");
                _earningsInfo = new RepoItemInfo(this, "Earnings", "?/?/li[@innertext='Earnings']", 30000, null, "0441b44a-75e7-4571-9c5f-27c9524e0bce");
                _historyInfo = new RepoItemInfo(this, "History", "?/?/li[@innertext='History']", 30000, null, "f7cba47e-2466-45bf-9f31-6ba65aafc37d");
                _licensesInfo = new RepoItemInfo(this, "Licenses", "?/?/li[@innertext='Licenses']", 30000, null, "e2a9fa75-e33f-4e27-9359-377dcdef1325");
                _ptosetupInfo = new RepoItemInfo(this, "PTOSetup", "?/?/li[@innertext='PTO Setup']", 30000, null, "1a541b7f-9362-4f53-9c7e-7c3f3effd54b");
                _litagptoInfo = new RepoItemInfo(this, "LiTagPTO", "?/?/li[@innertext='PTO']", 30000, null, "480b2dd0-112e-49af-b185-c5030f6165b1");
                _payhistoryInfo = new RepoItemInfo(this, "PayHistory", "?/?/li[@innertext='Pay History']", 30000, null, "4550005c-abb9-4525-a54f-5fac3570c98b");
                _taxesInfo = new RepoItemInfo(this, "Taxes", "?/?/li[@innertext='Taxes']", 30000, null, "4484973f-5ea0-494d-90cb-2d9efd1420a1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5c790e60-8f13-4c69-8197-7fd2f571bc9a")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5c790e60-8f13-4c69-8197-7fd2f571bc9a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Deductions item.
            /// </summary>
            [RepositoryItem("c01e2383-e9c4-4565-b771-190f973eba43")]
            public virtual Ranorex.LiTag Deductions
            {
                get
                {
                    return _deductionsInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Deductions item info.
            /// </summary>
            [RepositoryItemInfo("c01e2383-e9c4-4565-b771-190f973eba43")]
            public virtual RepoItemInfo DeductionsInfo
            {
                get
                {
                    return _deductionsInfo;
                }
            }

            /// <summary>
            /// The DirectDeposit item.
            /// </summary>
            [RepositoryItem("9442c2e2-d591-47b0-9964-f775bd261441")]
            public virtual Ranorex.LiTag DirectDeposit
            {
                get
                {
                    return _directdepositInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The DirectDeposit item info.
            /// </summary>
            [RepositoryItemInfo("9442c2e2-d591-47b0-9964-f775bd261441")]
            public virtual RepoItemInfo DirectDepositInfo
            {
                get
                {
                    return _directdepositInfo;
                }
            }

            /// <summary>
            /// The Documents item.
            /// </summary>
            [RepositoryItem("689f8271-ab06-4b52-9f35-91d373d1af68")]
            public virtual Ranorex.LiTag Documents
            {
                get
                {
                    return _documentsInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Documents item info.
            /// </summary>
            [RepositoryItemInfo("689f8271-ab06-4b52-9f35-91d373d1af68")]
            public virtual RepoItemInfo DocumentsInfo
            {
                get
                {
                    return _documentsInfo;
                }
            }

            /// <summary>
            /// The Earnings item.
            /// </summary>
            [RepositoryItem("0441b44a-75e7-4571-9c5f-27c9524e0bce")]
            public virtual Ranorex.LiTag Earnings
            {
                get
                {
                    return _earningsInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Earnings item info.
            /// </summary>
            [RepositoryItemInfo("0441b44a-75e7-4571-9c5f-27c9524e0bce")]
            public virtual RepoItemInfo EarningsInfo
            {
                get
                {
                    return _earningsInfo;
                }
            }

            /// <summary>
            /// The History item.
            /// </summary>
            [RepositoryItem("f7cba47e-2466-45bf-9f31-6ba65aafc37d")]
            public virtual Ranorex.LiTag History
            {
                get
                {
                    return _historyInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The History item info.
            /// </summary>
            [RepositoryItemInfo("f7cba47e-2466-45bf-9f31-6ba65aafc37d")]
            public virtual RepoItemInfo HistoryInfo
            {
                get
                {
                    return _historyInfo;
                }
            }

            /// <summary>
            /// The Licenses item.
            /// </summary>
            [RepositoryItem("e2a9fa75-e33f-4e27-9359-377dcdef1325")]
            public virtual Ranorex.LiTag Licenses
            {
                get
                {
                    return _licensesInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Licenses item info.
            /// </summary>
            [RepositoryItemInfo("e2a9fa75-e33f-4e27-9359-377dcdef1325")]
            public virtual RepoItemInfo LicensesInfo
            {
                get
                {
                    return _licensesInfo;
                }
            }

            /// <summary>
            /// The PTOSetup item.
            /// </summary>
            [RepositoryItem("1a541b7f-9362-4f53-9c7e-7c3f3effd54b")]
            public virtual Ranorex.LiTag PTOSetup
            {
                get
                {
                    return _ptosetupInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The PTOSetup item info.
            /// </summary>
            [RepositoryItemInfo("1a541b7f-9362-4f53-9c7e-7c3f3effd54b")]
            public virtual RepoItemInfo PTOSetupInfo
            {
                get
                {
                    return _ptosetupInfo;
                }
            }

            /// <summary>
            /// The LiTagPTO item.
            /// </summary>
            [RepositoryItem("480b2dd0-112e-49af-b185-c5030f6165b1")]
            public virtual Ranorex.LiTag LiTagPTO
            {
                get
                {
                    return _litagptoInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagPTO item info.
            /// </summary>
            [RepositoryItemInfo("480b2dd0-112e-49af-b185-c5030f6165b1")]
            public virtual RepoItemInfo LiTagPTOInfo
            {
                get
                {
                    return _litagptoInfo;
                }
            }

            /// <summary>
            /// The PayHistory item.
            /// </summary>
            [RepositoryItem("4550005c-abb9-4525-a54f-5fac3570c98b")]
            public virtual Ranorex.LiTag PayHistory
            {
                get
                {
                    return _payhistoryInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The PayHistory item info.
            /// </summary>
            [RepositoryItemInfo("4550005c-abb9-4525-a54f-5fac3570c98b")]
            public virtual RepoItemInfo PayHistoryInfo
            {
                get
                {
                    return _payhistoryInfo;
                }
            }

            /// <summary>
            /// The Taxes item.
            /// </summary>
            [RepositoryItem("4484973f-5ea0-494d-90cb-2d9efd1420a1")]
            public virtual Ranorex.LiTag Taxes
            {
                get
                {
                    return _taxesInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Taxes item info.
            /// </summary>
            [RepositoryItemInfo("4484973f-5ea0-494d-90cb-2d9efd1420a1")]
            public virtual RepoItemInfo TaxesInfo
            {
                get
                {
                    return _taxesInfo;
                }
            }
        }

        /// <summary>
        /// The CssVnm4clReactTabsFolder folder.
        /// </summary>
        [RepositoryFolder("c968c047-9605-45d4-ac8c-1b761d026102")]
        public partial class CssVnm4clReactTabsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _employeesactive132Info;
            RepoItemInfo _employeestotal160Info;
            RepoItemInfo _employeesleaveofabsence6Info;
            RepoItemInfo _employeesonstrike2Info;
            RepoItemInfo _employeesterminated20Info;

            /// <summary>
            /// Creates a new CssVnm4clReactTabs  folder.
            /// </summary>
            public CssVnm4clReactTabsFolder(RepoGenBaseFolder parentFolder) :
                    base("CssVnm4clReactTabs", ".//div[#'app']/div[2]/div[3]/div/div[1]", parentFolder, 30000, null, false, "c968c047-9605-45d4-ac8c-1b761d026102", "")
            {
                _employeesactive132Info = new RepoItemInfo(this, "EmployeesActive132", "?/?/h4[@innertext='Employees  - Active (132)']", 30000, null, "0ba76efb-4929-4597-a665-e83db7156fbf");
                _employeestotal160Info = new RepoItemInfo(this, "EmployeesTotal160", "?/?/h4[@innertext='Employees  - Total (160)']", 30000, null, "596fd64c-5bf6-42f8-9e3a-680ccaeb1aaf");
                _employeesleaveofabsence6Info = new RepoItemInfo(this, "EmployeesLeaveOfAbsence6", "?/?/h4[@innertext>'Employees  - Leave of absence']", 30000, null, "8367c9c4-b2e9-4572-ab85-8500787e668a");
                _employeesonstrike2Info = new RepoItemInfo(this, "EmployeesOnStrike2", "?/?/h4[@innertext>'Employees  - On strike (2']", 30000, null, "8f42b9a0-b79b-492c-b024-8ece796fca84");
                _employeesterminated20Info = new RepoItemInfo(this, "EmployeesTerminated20", "?/?/h4[@innertext>'Employees  - Terminated (']", 30000, null, "08fea008-a25f-4b1c-8fbe-7ce9f036007a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c968c047-9605-45d4-ac8c-1b761d026102")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c968c047-9605-45d4-ac8c-1b761d026102")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EmployeesActive132 item.
            /// </summary>
            [RepositoryItem("0ba76efb-4929-4597-a665-e83db7156fbf")]
            public virtual Ranorex.H4Tag EmployeesActive132
            {
                get
                {
                    return _employeesactive132Info.CreateAdapter<Ranorex.H4Tag>(true);
                }
            }

            /// <summary>
            /// The EmployeesActive132 item info.
            /// </summary>
            [RepositoryItemInfo("0ba76efb-4929-4597-a665-e83db7156fbf")]
            public virtual RepoItemInfo EmployeesActive132Info
            {
                get
                {
                    return _employeesactive132Info;
                }
            }

            /// <summary>
            /// The EmployeesTotal160 item.
            /// </summary>
            [RepositoryItem("596fd64c-5bf6-42f8-9e3a-680ccaeb1aaf")]
            public virtual Ranorex.H4Tag EmployeesTotal160
            {
                get
                {
                    return _employeestotal160Info.CreateAdapter<Ranorex.H4Tag>(true);
                }
            }

            /// <summary>
            /// The EmployeesTotal160 item info.
            /// </summary>
            [RepositoryItemInfo("596fd64c-5bf6-42f8-9e3a-680ccaeb1aaf")]
            public virtual RepoItemInfo EmployeesTotal160Info
            {
                get
                {
                    return _employeestotal160Info;
                }
            }

            /// <summary>
            /// The EmployeesLeaveOfAbsence6 item.
            /// </summary>
            [RepositoryItem("8367c9c4-b2e9-4572-ab85-8500787e668a")]
            public virtual Ranorex.H4Tag EmployeesLeaveOfAbsence6
            {
                get
                {
                    return _employeesleaveofabsence6Info.CreateAdapter<Ranorex.H4Tag>(true);
                }
            }

            /// <summary>
            /// The EmployeesLeaveOfAbsence6 item info.
            /// </summary>
            [RepositoryItemInfo("8367c9c4-b2e9-4572-ab85-8500787e668a")]
            public virtual RepoItemInfo EmployeesLeaveOfAbsence6Info
            {
                get
                {
                    return _employeesleaveofabsence6Info;
                }
            }

            /// <summary>
            /// The EmployeesOnStrike2 item.
            /// </summary>
            [RepositoryItem("8f42b9a0-b79b-492c-b024-8ece796fca84")]
            public virtual Ranorex.H4Tag EmployeesOnStrike2
            {
                get
                {
                    return _employeesonstrike2Info.CreateAdapter<Ranorex.H4Tag>(true);
                }
            }

            /// <summary>
            /// The EmployeesOnStrike2 item info.
            /// </summary>
            [RepositoryItemInfo("8f42b9a0-b79b-492c-b024-8ece796fca84")]
            public virtual RepoItemInfo EmployeesOnStrike2Info
            {
                get
                {
                    return _employeesonstrike2Info;
                }
            }

            /// <summary>
            /// The EmployeesTerminated20 item.
            /// </summary>
            [RepositoryItem("08fea008-a25f-4b1c-8fbe-7ce9f036007a")]
            public virtual Ranorex.H4Tag EmployeesTerminated20
            {
                get
                {
                    return _employeesterminated20Info.CreateAdapter<Ranorex.H4Tag>(true);
                }
            }

            /// <summary>
            /// The EmployeesTerminated20 item info.
            /// </summary>
            [RepositoryItemInfo("08fea008-a25f-4b1c-8fbe-7ce9f036007a")]
            public virtual RepoItemInfo EmployeesTerminated20Info
            {
                get
                {
                    return _employeesterminated20Info;
                }
            }
        }

        /// <summary>
        /// The MyFrankCrumAppFolder folder.
        /// </summary>
        [RepositoryFolder("e02b0ef2-fe8d-4d4c-89ac-ddc5221f14bc")]
        public partial class MyFrankCrumAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginbuttonInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _compselectInfo;

            /// <summary>
            /// Creates a new MyFrankCrum  folder.
            /// </summary>
            public MyFrankCrumAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyFrankCrum", "/dom[@domain='devmfc.frankcrum.com']", parentFolder, 30000, null, false, "e02b0ef2-fe8d-4d4c-89ac-ddc5221f14bc", "")
            {
                _usernameInfo = new RepoItemInfo(this, "Username", ".//input[#'username']", 30000, null, "dae14d42-0356-417b-9909-606bdede9e58");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//div[#'app']//form[@action='https://devmfc.frankcrum.com/login']/div[2]/input[@type='password']", 30000, null, "412c74cf-dc5a-4923-abfd-d0df44deb072");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", ".//button[#'login-button']", 30000, null, "5f2dc3f0-e054-4d98-957f-563cc77b128a");
                _textInfo = new RepoItemInfo(this, "Text", ".//div[#'modal-wrapper']/div/div/div[4]/div/div[1]/?/?/input[@type='text']", 30000, null, "2c2381c4-c30c-4b42-b588-e26ac722476e");
                _compselectInfo = new RepoItemInfo(this, "compselect", ".//div[#'company-list-scroll']/div/?/?/button[@innertext>$CompName]", 30000, null, "0bf98207-7145-403e-bdbb-7408bdc8115b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e02b0ef2-fe8d-4d4c-89ac-ddc5221f14bc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e02b0ef2-fe8d-4d4c-89ac-ddc5221f14bc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("dae14d42-0356-417b-9909-606bdede9e58")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("dae14d42-0356-417b-9909-606bdede9e58")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("412c74cf-dc5a-4923-abfd-d0df44deb072")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("412c74cf-dc5a-4923-abfd-d0df44deb072")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("5f2dc3f0-e054-4d98-957f-563cc77b128a")]
            public virtual Ranorex.ButtonTag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("5f2dc3f0-e054-4d98-957f-563cc77b128a")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("2c2381c4-c30c-4b42-b588-e26ac722476e")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("2c2381c4-c30c-4b42-b588-e26ac722476e")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The compselect item.
            /// </summary>
            [RepositoryItem("0bf98207-7145-403e-bdbb-7408bdc8115b")]
            public virtual Ranorex.ButtonTag compselect
            {
                get
                {
                    return _compselectInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The compselect item info.
            /// </summary>
            [RepositoryItemInfo("0bf98207-7145-403e-bdbb-7408bdc8115b")]
            public virtual RepoItemInfo compselectInfo
            {
                get
                {
                    return _compselectInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("803f8440-3af5-460b-a814-d1d1b413f407")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ranorexstudio2runningwindowsInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "803f8440-3af5-460b-a814-d1d1b413f407", "")
            {
                _ranorexstudio2runningwindowsInfo = new RepoItemInfo(this, "RanorexStudio2RunningWindows", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[9]", 30000, null, "83da23ea-c932-4c3c-827a-1d455c26d0c5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("803f8440-3af5-460b-a814-d1d1b413f407")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("803f8440-3af5-460b-a814-d1d1b413f407")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RanorexStudio2RunningWindows item.
            /// </summary>
            [RepositoryItem("83da23ea-c932-4c3c-827a-1d455c26d0c5")]
            public virtual Ranorex.Button RanorexStudio2RunningWindows
            {
                get
                {
                    return _ranorexstudio2runningwindowsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RanorexStudio2RunningWindows item info.
            /// </summary>
            [RepositoryItemInfo("83da23ea-c932-4c3c-827a-1d455c26d0c5")]
            public virtual RepoItemInfo RanorexStudio2RunningWindowsInfo
            {
                get
                {
                    return _ranorexstudio2runningwindowsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
