///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyFrankCrum_EMP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyFrankCrum_EMPRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("57aa7af5-e1bb-4d86-b1a0-d72cef37e59c")]
    public partial class MyFrankCrum_EMPRepository : RepoGenBaseFolder
    {
        static MyFrankCrum_EMPRepository instance = new MyFrankCrum_EMPRepository();
        MyFrankCrum_EMPRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyFrankCrum_EMPRepositoryFolders.MyFrankCrumAppFolder _myfrankcrum;

        /// <summary>
        /// Gets the singleton class instance representing the MyFrankCrum_EMPRepository element repository.
        /// </summary>
        [RepositoryFolder("57aa7af5-e1bb-4d86-b1a0-d72cef37e59c")]
        public static MyFrankCrum_EMPRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyFrankCrum_EMPRepository() 
            : base("MyFrankCrum_EMPRepository", "/", null, 0, false, "57aa7af5-e1bb-4d86-b1a0-d72cef37e59c", ".\\RepositoryImages\\MyFrankCrum_EMPRepository57aa7af5.rximgres")
        {
            _applicationundertest = new MyFrankCrum_EMPRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _myfrankcrum = new MyFrankCrum_EMPRepositoryFolders.MyFrankCrumAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("57aa7af5-e1bb-4d86-b1a0-d72cef37e59c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("4adb2402-d0f1-4185-819f-54d35157c656")]
        public virtual MyFrankCrum_EMPRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The MyFrankCrum folder.
        /// </summary>
        [RepositoryFolder("e02b0ef2-fe8d-4d4c-89ac-ddc5221f14bc")]
        public virtual MyFrankCrum_EMPRepositoryFolders.MyFrankCrumAppFolder MyFrankCrum
        {
            get { return _myfrankcrum; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyFrankCrum_EMPRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("4adb2402-d0f1-4185-819f-54d35157c656")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='devmfc.frankcrum.com']", parentFolder, 30000, null, false, "4adb2402-d0f1-4185-819f-54d35157c656", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4adb2402-d0f1-4185-819f-54d35157c656")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4adb2402-d0f1-4185-819f-54d35157c656")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The MyFrankCrumAppFolder folder.
        /// </summary>
        [RepositoryFolder("e02b0ef2-fe8d-4d4c-89ac-ddc5221f14bc")]
        public partial class MyFrankCrumAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginbuttonInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _a0f21thsnationalllcInfo;

            /// <summary>
            /// Creates a new MyFrankCrum  folder.
            /// </summary>
            public MyFrankCrumAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyFrankCrum", "/dom[@domain='devmfc.frankcrum.com']", parentFolder, 30000, null, false, "e02b0ef2-fe8d-4d4c-89ac-ddc5221f14bc", "")
            {
                _usernameInfo = new RepoItemInfo(this, "Username", ".//input[#'username']", 30000, null, "dae14d42-0356-417b-9909-606bdede9e58");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "412c74cf-dc5a-4923-abfd-d0df44deb072");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", ".//button[#'login-button']", 30000, null, "5f2dc3f0-e054-4d98-957f-563cc77b128a");
                _textInfo = new RepoItemInfo(this, "Text", ".//div[#'modal-wrapper']/div/div/div[4]/div/div[1]/?/?/input[@type='text']", 30000, null, "2c2381c4-c30c-4b42-b588-e26ac722476e");
                _a0f21thsnationalllcInfo = new RepoItemInfo(this, "A0F21THSNATIONALLLC", ".//div[#'company-list-scroll']//button[@innertext='A0F21-THS NATIONAL LLC']", 30000, null, "0bf98207-7145-403e-bdbb-7408bdc8115b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e02b0ef2-fe8d-4d4c-89ac-ddc5221f14bc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e02b0ef2-fe8d-4d4c-89ac-ddc5221f14bc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("dae14d42-0356-417b-9909-606bdede9e58")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("dae14d42-0356-417b-9909-606bdede9e58")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("412c74cf-dc5a-4923-abfd-d0df44deb072")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("412c74cf-dc5a-4923-abfd-d0df44deb072")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("5f2dc3f0-e054-4d98-957f-563cc77b128a")]
            public virtual Ranorex.ButtonTag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("5f2dc3f0-e054-4d98-957f-563cc77b128a")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("2c2381c4-c30c-4b42-b588-e26ac722476e")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("2c2381c4-c30c-4b42-b588-e26ac722476e")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The A0F21THSNATIONALLLC item.
            /// </summary>
            [RepositoryItem("0bf98207-7145-403e-bdbb-7408bdc8115b")]
            public virtual Ranorex.ButtonTag A0F21THSNATIONALLLC
            {
                get
                {
                    return _a0f21thsnationalllcInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The A0F21THSNATIONALLLC item info.
            /// </summary>
            [RepositoryItemInfo("0bf98207-7145-403e-bdbb-7408bdc8115b")]
            public virtual RepoItemInfo A0F21THSNATIONALLLCInfo
            {
                get
                {
                    return _a0f21thsnationalllcInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
