///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyFrankCrum_EMP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PersonalTabContacts recording.
    /// </summary>
    [TestModule("0c0609f2-ef3d-475b-b875-50dfcf762749", ModuleType.Recording, 1)]
    public partial class PersonalTabContacts : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyFrankCrum_EMPRepository repository.
        /// </summary>
        public static MyFrankCrum_EMPRepository repo = MyFrankCrum_EMPRepository.Instance;

        static PersonalTabContacts instance = new PersonalTabContacts();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PersonalTabContacts()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PersonalTabContacts Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeDivTag.AddNewContact' at Center.", repo.ApplicationUnderTest.SomeDivTag.AddNewContactInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.SomeDivTag.AddNewContact.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CssKynsejIndicatorContainerMfcSelect' at Center.", repo.ApplicationUnderTest.CssKynsejIndicatorContainerMfcSelectInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.CssKynsejIndicatorContainerMfcSelect.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeDivTag.Brother' at Center.", repo.ApplicationUnderTest.SomeDivTag.BrotherInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.SomeDivTag.Brother.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.InputTagSsn' at Center.", repo.ApplicationUnderTest.InputTagSsnInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.InputTagSsn.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '234565434' with focus on 'ApplicationUnderTest.InputTagSsn'.", repo.ApplicationUnderTest.InputTagSsnInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.InputTagSsn.PressKeys("234565434");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.FirstName1' at Center.", repo.ApplicationUnderTest.FirstName1Info, new RecordItemIndex(5));
            repo.ApplicationUnderTest.FirstName1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Sadanand' with focus on 'ApplicationUnderTest.FirstName1'.", repo.ApplicationUnderTest.FirstName1Info, new RecordItemIndex(6));
            repo.ApplicationUnderTest.FirstName1.PressKeys("Sadanand");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MiddleName2' at Center.", repo.ApplicationUnderTest.MiddleName2Info, new RecordItemIndex(7));
            repo.ApplicationUnderTest.MiddleName2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'L' with focus on 'ApplicationUnderTest.MiddleName2'.", repo.ApplicationUnderTest.MiddleName2Info, new RecordItemIndex(8));
            repo.ApplicationUnderTest.MiddleName2.PressKeys("L");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LastName2' at Center.", repo.ApplicationUnderTest.LastName2Info, new RecordItemIndex(9));
            repo.ApplicationUnderTest.LastName2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'GUpta' with focus on 'ApplicationUnderTest.LastName2'.", repo.ApplicationUnderTest.LastName2Info, new RecordItemIndex(10));
            repo.ApplicationUnderTest.LastName2.PressKeys("GUpta");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.FormerName' at Center.", repo.ApplicationUnderTest.FormerNameInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.FormerName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Saddu' with focus on 'ApplicationUnderTest.FormerName'.", repo.ApplicationUnderTest.FormerNameInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.FormerName.PressKeys("Saddu");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CssKynsejIndicatorContainerMfcSelect1' at Center.", repo.ApplicationUnderTest.CssKynsejIndicatorContainerMfcSelect1Info, new RecordItemIndex(13));
            repo.ApplicationUnderTest.CssKynsejIndicatorContainerMfcSelect1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeDivTag.DivTagSr' at Center.", repo.ApplicationUnderTest.SomeDivTag.DivTagSrInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.SomeDivTag.DivTagSr.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeDivTag.FaCaretDownFas1' at Center.", repo.ApplicationUnderTest.SomeDivTag.FaCaretDownFas1Info, new RecordItemIndex(15));
            repo.ApplicationUnderTest.SomeDivTag.FaCaretDownFas1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Male' at Center.", repo.ApplicationUnderTest.MaleInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.Male.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BirthDate1' at Center.", repo.ApplicationUnderTest.BirthDate1Info, new RecordItemIndex(17));
            repo.ApplicationUnderTest.BirthDate1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '07101994' with focus on 'ApplicationUnderTest.BirthDate1'.", repo.ApplicationUnderTest.BirthDate1Info, new RecordItemIndex(18));
            repo.ApplicationUnderTest.BirthDate1.PressKeys("07101994");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MarriageDate' at Center.", repo.ApplicationUnderTest.MarriageDateInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.MarriageDate.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0711/2019' with focus on 'ApplicationUnderTest.MarriageDate'.", repo.ApplicationUnderTest.MarriageDateInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.MarriageDate.PressKeys("0711/2019");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
